---
title: "Exploratory analysis"
output: github_document
---


```{r}
library (tidyverse)
```

## load the weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match (
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything()) # put name and id in the front, everthing comes follow

weather_df
```

## `group by`

```{r}
weather_df |>
  group_by(names, month)
```

## counting things

count month / name observation
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(n_obs = n())
```

we can use `count`
```{r}
weather_df |>
  count (name, month, name = "n_obs")
```

** NEVER ** use base R's `table`
```{r, eval = FALSE}
weather_df |>
  pull(month) |>
  table()
```

other helpful counters
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```

## a digression on 2x2 tables

```{r}
weather_df |>
  filter (name != "Waikiki_HA") |> #! = not equal to 
  mutate (
    cold = case_when( # when xx condition is true, then...
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  )|>
  group by (name, cold) |>
  summarize (count = n()) 

```

quicker way:
```{r}
weather_df |>
  filter (name != "Waikiki_HA") |> #! = not equal to 
  mutate (
    cold = case_when( # when xx condition is true, then...
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  )|>
  janitor:: tabyl(name, cold)
```



