---
title: "visualization"
subtitle: "part 2"
output: github_document
---


```{r}
library (tidyverse)
library (patchwork)
```

## load the weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match (
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything()) # put name and id in the front, everthing comes follow

```

## Remember this plot .. ?

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5)
```

## labels

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa paackage; temperature in 2017."
  ) ## default color: red, blue, green
```

## scales

start with the same plot

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa paackage; temperature in 2017."
  ) +
  scale_x_continuous( #x-axis for continuous variables
    breaks = c(-15, 0, 15), # x-axis range
    labels = c("-15 C", "0", "15") # adding tick mark
  ) +
  scale_y_continuous(
    trans = "sqrt", #square root; "log" for log;
    position = "right", # put y-aix on right side
  )
```

look at color scales
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa paackage; temperature in 2017."
  ) +
  scale_color_hue(
    name = "Location", #change the title of caption label
    h = c(100,300)) # light purple, turquoise, green
```

or

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa paackage; temperature in 2017."
  ) +
  viridis::scale_color_viridis ( # viridis for continuous variable
    name = "Location", #change the title of ledgend
    discrete = TURE #tell R it's discrete variable
    ) # yellow, purple, turquoise
```

## themes

shift the ledgend.
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa paackage; temperature in 2017."
  ) +
  viridis::scale_color_viridis ( # viridis for continuous variable
    name = "Location", #change the title of caption label
    discrete = TURE  ) + #tell R it's discrete variable
   theme (legned.position = "bottom")
  
```

change the overall theme
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maximum daily temperature (C)",
    caption = "Data from rnoaa paackage; temperature in 2017."
  ) +
  viridis::scale_color_viridis (
    name = "Location", 
    discrete = TURE)+
 
  theme_bw () #change background to back and white
  theme_minimal () # same as default, but without the frame box
  them_classic ()
  ggthemes::theme_economist()
  ggthemes:: theme_excel ()
```

## setting options
setting option for later use
```{r, eval = FALSE}
library (tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme (legend.position = "bottom"))

options (
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Data args in `geom`

```{r}
central_park = 
  weather_df |>
  fliter(name == "CentralPark_NY")

waikiki = 
  weather_df |>
  fliter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  geom_line(data = central_park) ## draw line for diff dataset
```














